[package]
name = "tt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
image = "0.24.7"
ascii = {path = "./ascii"}

# [profile.dev]
# opt-level = 1